version: "3.7"

services:
  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: Mfcd62!!Mfcd62!!
      MARIADB_DATABASE: glpi
      MARIADB_USER: glpi
      MARIADB_PASSWORD: 1234554321
      TZ: America/Sao_Paulo
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - network_public
    #ports:
    #  - 3307:3306
    restart: always
    deploy:
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1'
          memory: 1024M
  
  glpi:
    image: astraonline/glpi:10.0.15
    restart: always
    depends_on:
      - mariadb
    links:
      - "mariadb:mariadb"
    environment:
      TIMEZONE: America/Sao_Paulo
      VERSION: 10.0.2
      UPLOAD_MAX_FILESIZE: 100M
      POST_MAX_FILESIZE: 50M
    volumes:
      - glpi_data:/var/www/html
    networks:
      - network_public
    #ports:
    #  - "8002:80"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.http.routers.glpi.rule=Host(`seudominio.com.br`)
        - traefik.http.services.glpi.loadbalancer.server.port=80
        - traefik.http.routers.glpi.service=glpi
        - traefik.http.routers.glpi.tls.certresolver=letsencryptresolver
        - traefik.http.routers.glpi.entrypoints=websecure
        - traefik.http.routers.glpi.tls=true

volumes:
  glpi_data:
    external: true
    name: glpi_data
  mariadb_data:
    external: true
    name: mariadb_data

networks:
  network_public:
    external: true
    name: network_public
